CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  nama VARCHAR(225) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(225) NOT NULL,
  role VARCHAR(20) NOT DEFAULT 'petugas'
);
